### ISSUE TITLE
Make error if  '--with-nemea' is used

### ISSUE THREAD

**Issue by Mitsj0l** [CESNET/ipfixprobe#101]
Hi all,

It seems while adding the " --with-nemea" build option, this error is thrown across version v4, v4.4, v4.5 and v4.6:
Is something missing or is anyone else seeing this issue? 
`
user@user-virtual-machine:~/ipfixprobe-4.6.0$ ./configure --with-pcap --with-nemea
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking how to run the C preprocessor... gcc -E
checking for rpmbuild... no
checking for debuild... no
checking for arpa/inet.h... yes
checking for inttypes.h... (cached) yes
checking for netdb.h... yes
checking for netinet/in.h... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for sys/socket.h... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for _Bool... yes
checking for stdbool.h that conforms to C99... yes
checking for inline... inline
checking for int32_t... yes
checking for int8_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking whether byte ordering is bigendian... no
checking for __atomic_store in -latomic... yes
checking for EVP_PKEY_CTX_new_id in -lcrypto... yes
checking for linux/if_packet.h... yes
checking for net/ethernet.h... yes
checking for net/if.h... yes
checking for ifaddrs.h... yes
checking for struct tpacket3_hdr... yes
checking for pcap.h... yes
checking for pcap_open_live in -lpcap... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libtrap... yes
checking for trap2man.sh... /usr/bin/nemea/trap2man.sh
checking for ur_processor.sh... /usr/bin/nemea/ur_processor.sh
checking for unirec... no
checking for unirec in parent directory... checking for unirec/unirec.h... yes
checking for unirec/inline.h... yes
checking for unirec/ipaddr_cpp.h... no
no
checking for unirec/ipaddr.h... yes
checking for unirec/links.h... yes
checking for unirec/ur_time.h... yes
checking for unirec/ur_values.h... yes
checking for ur_create_template in -lunirec... yes
checking for error_at_line... yes
checking for working strtod... yes
checking for gettimeofday... yes
checking for inet_ntoa... yes
checking for memset... yes
checking for socket... yes
checking for strchr... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for strtoull... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating ipfixprobe.spec
config.status: creating ipfixprobe.bash
config.status: creating input/nfbCInterface/Makefile
config.status: creating init/Makefile
config.status: creating tests/Makefile
config.status: creating tests/functional/Makefile
config.status: creating tests/unit/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

------------------------------------------------------------------------
ipfixprobe 4.6.0
------------------------------------------------------------------------

Configuration Options Summary:

  ASM.(32 bit only)......:
  Static binary..........:

Documentation............:

UniRec processor.........: /usr/bin/nemea/ur_processor.sh
trap2man.sh..............: /usr/bin/nemea/trap2man.sh
Compilation..............: make (or gmake)
  CPPFLAGS...............: -I/usr/local/include -DNDEBUG=1
  CFLAGS.................:  -Wall -g -O3
  CXXFLAGS...............:  -Wall -g -O3
  LDFLAGS................:
  LIBS...................:  -L/usr/local/lib -lssl -lcrypto -lrt -ltrap -lpcap -lcrypto
Enforced NEMEA (for copr): no
FlexProbe Data Interface.: no
DPDK Interface...........: no

Installation.............: make install (as root if needed, with 'su' or 'sudo')
  prefix.................: /usr/local

user@user-virtual-machine:~/ipfixprobe-4.6.0$ make
/usr/bin/nemea/ur_processor.sh -i ./ -o ./
make  all-recursive
make[1]: Entering directory '/home/user/ipfixprobe-4.6.0'
Making all in .
make[2]: Entering directory '/home/user/ipfixprobe-4.6.0'
  CXX      input/ipfixprobe-benchmark.o
  CXX      input/ipfixprobe-parser.o
  CXX      input/ipfixprobe-raw.o
  CXX      input/ipfixprobe-pcap.o
  CXX      storage/ipfixprobe-cache.o
  CC       storage/ipfixprobe-xxhash.o
  CXX      output/ipfixprobe-ipfix.o
  CXX      output/ipfixprobe-text.o
  CXX      output/ipfixprobe-ipfix-basiclist.o
  CXX      output/ipfixprobe-unirec.o
  CC       ipfixprobe-fields.o
  CXX      process/ipfixprobe-http.o
In file included from ./fields.h:5,
                 from process/http.hpp:55,
                 from process/http.cpp:54:
process/http.hpp: In member function ‘virtual void ipxp::RecordExtHTTP::fill_unirec(ur_template_t*, void*)’:
process/http.hpp:119:36: error: ‘F_HTTP_REQUEST_METHOD’ was not declared in this scope
  119 |       ur_set_string(tmplt, record, F_HTTP_REQUEST_METHOD, method);
      |                                    ^~~~~~~~~~~~~~~~~~~~~
process/http.hpp:120:36: error: ‘F_HTTP_REQUEST_HOST’ was not declared in this scope
  120 |       ur_set_string(tmplt, record, F_HTTP_REQUEST_HOST, host);
      |                                    ^~~~~~~~~~~~~~~~~~~
process/http.hpp:121:36: error: ‘F_HTTP_REQUEST_URL’ was not declared in this scope; did you mean ‘SIP_REQUEST_URI’?
  121 |       ur_set_string(tmplt, record, F_HTTP_REQUEST_URL, uri);
      |                                    ^~~~~~~~~~~~~~~~~~
process/http.hpp:122:36: error: ‘F_HTTP_REQUEST_AGENT’ was not declared in this scope
  122 |       ur_set_string(tmplt, record, F_HTTP_REQUEST_AGENT, user_agent);
      |                                    ^~~~~~~~~~~~~~~~~~~~
process/http.hpp:123:36: error: ‘F_HTTP_REQUEST_REFERER’ was not declared in this scope
  123 |       ur_set_string(tmplt, record, F_HTTP_REQUEST_REFERER, referer);
      |                                    ^~~~~~~~~~~~~~~~~~~~~~
process/http.hpp:124:36: error: ‘F_HTTP_RESPONSE_CONTENT_TYPE’ was not declared in this scope
  124 |       ur_set_string(tmplt, record, F_HTTP_RESPONSE_CONTENT_TYPE, content_type);
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
process/http.hpp:125:29: error: ‘F_HTTP_RESPONSE_STATUS_CODE_T’ was not declared in this scope
  125 |       ur_set(tmplt, record, F_HTTP_RESPONSE_STATUS_CODE, code);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
process/http.hpp:125:7: error: expected primary-expression before ‘)’ token
  125 |       ur_set(tmplt, record, F_HTTP_RESPONSE_STATUS_CODE, code);
      |       ^~~~~~
process/http.hpp:125:29: error: ‘F_HTTP_RESPONSE_STATUS_CODE’ was not declared in this scope
  125 |       ur_set(tmplt, record, F_HTTP_RESPONSE_STATUS_CODE, code);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1980: process/ipfixprobe-http.o] Error 1
make[2]: Leaving directory '/home/user/ipfixprobe-4.6.0'
make[1]: *** [Makefile:2573: all-recursive] Error 1
make[1]: Leaving directory '/home/user/ipfixprobe-4.6.0'
make: *** [Makefile:927: all] Error 2
`

**Comment by cejkato2** [comment]
Hello, I'm sorry for the delay. In case this issue still persists, I've tested the following simple steps in podman containers with:

# 1. ubuntu 22.04

`podman run -ti --rm ubuntu:22.04 bash`

```
# install dependencies into clean Ubuntu 22.04 docker container:
apt update
apt -y install build-essential
apt -y install git autoconf libtool libssl-dev libxml2-dev libpcap-dev libatomic1

# clone and build nemea-framework (dependency for ipfixprobe --with-nemea)
git clone https://github.com/cesnet/nemea-framework
cd nemea-framework/
autoupdate
./bootstrap.sh &&./configure -q --prefix=/usr &&make install -j5

# clone and build ipfixprobe
cd ..
git clone https://github.com/cesnet/ipfixprobe
cd ipfixprobe/
autoreconf -i
./configure --with-nemea --with-pcap -q
make -j10

# test ipfixprobe:
./ipfixprobe -h input
./ipfixprobe -i 'pcap;f=./pcaps/more_initial_samples.pcapng' -p basicplus -o text
./ipfixprobe -i 'pcap;f=./pcaps/more_initial_samples.pcapng' -p basicplus -o 'unirec;i=f:/tmp/output.trapcap;p=basicplus'
```

# 2.  OracleLinux 8 (oraclelinux:8-slim)

`podman run -ti --rm oraclelinux:8-slim`

```
# Install dependencies in oraclelinux:8-slim

microdnf -y install oracle-epel-release-el8
yum-config-manager --enable ol8_codeready_builder
dnf -y install gcc gcc-c++ libtool autoconf make pkgconfig git libpcap-devel libxml2-devel openssl-devel file diffutils libatomic

# clone and build nemea-framework (dependency for ipfixprobe --with-nemea)
git clone https://github.com/cesnet/nemea-framework
cd nemea-framework
./bootstrap.sh &&./configure -q --prefix=/usr &&make install -j5

# clone and build ipfixprobe
cd ..
git clone https://github.com/cesnet/ipfixprobe
cd ipfixprobe/
autoreconf -i && ./configure --with-nemea --with-pcap -q && make -j10

# test ipfixprobe:
./ipfixprobe -h input
./ipfixprobe -i 'pcap;f=./pcaps/more_initial_samples.pcapng' -p basicplus -o text
./ipfixprobe -i 'pcap;f=./pcaps/more_initial_samples.pcapng' -p basicplus -o 'unirec;i=f:/tmp/output.trapcap;p=basicplus'
```

Both finished successfuly with NEMEA output plugin.

Note: ubuntu complained about obsoleted M4 macros so there is autoupdate command, which was suggested automatically by autoreconf.

# Thoughts:

* what distribution was used for the virtual machine?
* check if nemea-framework is really installed; the UniRec fields (such as `F_HTTP_REQUEST_METHOD`)  are generated by `/usr/bin/nemea/ur_processor.sh`, which seems to be installed - is it a correct version?
* try to `make clean && make` in ipfixprobe

**Comment by rrader** [comment]
I had the same issue, and it was the old version of `ur_processor.sh` which does not account for `.hpp` files, only `.h`.
Reinstalling Nemea-framework/unirec helped, as well as just replacing the `/usr/bin/nemea/ur_processor.sh` with the one from master branch (https://github.com/CESNET/Nemea-Framework/blob/master/unirec/ur_processor.sh)

**Comment by cejkato2** [comment]
> I had the same issue, and it was the old version of `ur_processor.sh` which does not account for `.hpp` files, only `.h`.
> Reinstalling Nemea-framework/unirec helped, as well as just replacing the `/usr/bin/nemea/ur_processor.sh` with the one from master branch (https://github.com/CESNET/Nemea-Framework/blob/master/unirec/ur_processor.sh)

Yes exactly! Latest installed nemea-framework - UniRec is required to compile ipfixprobe with unirec output plugin. Thanks for this hint.
