### ISSUE TITLE
NDP input: Incorrect timestamps with new NDK firmwares

### ISSUE THREAD

**Issue by Lukas955** [CESNET/ipfixprobe#198]
Hello,

the current NDP input module only supports timestamps in Hanic firmware format, which is no longer being developed.  

Unfortunately, new firmwares for FPGA cards based on the NDK platform (especially NDK-APP-NIC for the metering infrastructure) use a different metadata format, which causes the current software to use invalid timestamps for individual packets and thus flows. The format is also newly flexible and the card can use a different format (from the defined set) even for each individual packet depending on the configuration and firmware application.

The input module should read the DeviceTree on startup. Find and process the "cesnet,ofm,ndp-header-rx" components in it, which contain the "header_id" and name/size/position of the individual metadata items. Then, when reading packets from the NIC, it should use the [NDP function](https://github.com/CESNET/ndk-sw/blob/bcca1ef6c8a8a353e29638c08fc45264195be625/libnfb/include/nfb/ndp.h#L66C63-L66C63) to find out for each individual packet what specific header it received and extract the timestamp accordingly.

For backward compatibility reasons, the old fixed format should be used when older firmware (i.e. Hanic) is detected.

Lukas

**Comment by SiskaPavel** [comment]
Resolved in #202
