### ISSUE TITLE
Create Git tags for releases

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [CESNET/ipfixprobe#226]
Seems like there has been two releases since [4.11.1](https://github.com/CESNET/ipfixprobe/releases/tag/v4.11.1), [4.12.0](https://github.com/CESNET/ipfixprobe/commit/564b032a16684f2e87407250daa64e371d7dbaa0) and [4.13.0](https://github.com/CESNET/ipfixprobe/commit/bc2024b5c268268870bd9b4c99e09eab80583117) neither of which currently have a tag in this Git repository.

**Comment by FestplattenSchnitzel** [comment]
Still no tag for [4.14.0](https://github.com/CESNET/ipfixprobe/commit/97cf479ba64b63276ad1c9c8af2a544dd03e1104) unfortunately.

**Comment by SiskaPavel** [comment]
Added tag [v4.15.0](https://github.com/CESNET/ipfixprobe/releases/tag/v4.15.0)
