### ISSUE TITLE
IPFIXProbe does not work on RPi4

### ISSUE THREAD

**Issue by MigNov** [CESNET/ipfixprobe#80]
Hello,
I've been trying to compile IPFIXProbe project on the RPi4 and RPi CM4 but it seems to be not supported as it's returning the "Bus error". According to several sources, including https://forums.raspberrypi.com/viewtopic.php?f=33&t=102400, it seems to have the issue with hard-floating ABI but when I try to set the CFLAGS to "-mcpu=cortex-a72 -mfloat-abi=soft -mfpu=crypto-neon-fp-armv8" it breaks the compilation entirely. Is this project going to support ARM/RPi4?

Thanks a lot for your answer,
Michal

**Comment by MigNov** [comment]
Addressed by: https://github.com/CESNET/ipfixprobe/pull/83

**Comment by hynekkar** [comment]
Hello, this bug was resolved by xxhash library update in #84. Thanks for finding it. 

Karel

**Comment by MigNov** [comment]
Hello Karel,
thanks for merging the fix / xxhash library update.

Michal
